apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workspace-controller-system

namePrefix: nb-

resources:
- deployment.yaml
- service.yaml

images:
- name: nb-frontend

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kubeflow-notebooks
